---
deployment:
  tasks:
    - export DEPLOYPATH=/home/crocust1/public_html
    # Clone the Laravel project repository
    - git clone --depth=1 https://github.com/MirobidKobilov/CrocusNew.git $DEPLOYPATH
    # Install composer dependencies
    - cd $DEPLOYPATH && composer install --ignore-platform-reqs
    # Remove .git directory to avoid exposure of sensitive data
    - rm -rf $DEPLOYPATH/.git
    # Move the project to the deployment path
    - /bin/cp -R $TEMP_DEPLOYPATH/* $DEPLOYPATH
    - /bin/cp -R $TEMP_DEPLOYPATH/.[^.]* $DEPLOYPATH 2>/dev/null || :
    # Clean up temporary deployment path
    - rm -rf $TEMP_DEPLOYPATH
    # Set proper permissions for Laravel directories
    - chmod -R 755 $DEPLOYPATH/storage
    - chmod -R 755 $DEPLOYPATH/bootstrap/cache
    # Generate Laravel application key
    - php $DEPLOYPATH/artisan key:generate --force
    # Run database migrations
    - php $DEPLOYPATH/artisan migrate --force
    # Clear Laravel cache
    - php $DEPLOYPATH/artisan cache:clear
